apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-flask-app
  template:
    metadata:
      labels:
        app: python-flask-app
    spec:
      containers:
        - name: flask-app
          image: itsverysimple/flask-k8s:latest 
          #to change the image, we need to update the image tag and then apply the deployment.yaml file again
          #use itsverysimple/python-k8s:v1-1 for the version and new tag purpose
          ports:
            - containerPort: 5000
