#Service for region A 

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-v1
  namespace: region-a
spec:
  selector:
    app: nginx
    version: v1
  ports:
  - port: 80
    targetPort: 80


---
#Service for region B

apiVersion: v1
kind: Service   
metadata:
  name: nginx-service-v2
  namespace: region-b
spec:
  selector:
    app: nginx
    version: v2
  ports:
  - port: 80
    targetPort: 80