apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: hashicorp/http-echo:0.2.3
        args:
        - "-text=Hello from Backend"
        - "-listen=:3000"
        ports:
        - containerPort: 3000

