apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-deployment
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bd-app 
  template:
    metadata:
      labels:
        app: bd-app 
    spec:
      containers:
      - name: nodejs-container
        image: node:latest
        command: ["sh", "-c", "echo 'Hello from Node.js container!'"]
        ports:
        - containerPort: 3000