apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-blue-app
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-blue-container
          image: itsverysimple/python-bg:latest
          ports:
            - containerPort: 5000
              env:
              - name: ENVIRONMENT
                value: "blue"
                readinessProbe:
                  httpGet:
                    path: /health
                    port: 5000
                  initialDelaySeconds: 5
                  periodSeconds: 10
              livenessProbe:
                httpGet:
                  path: /health
                  port: 5000
                initialDelaySeconds: 15
                periodSeconds: 20 
                