apiVersion: v1
kind: Service
metadata: 
  name: python-bg-live-service
  namespace: prod
spec:
  type: NodePort
  selector: 
    app: python-bg-live-app
    version: blue
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30008