version: "3.8"

services:
  lb:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - bg-net
    configs:
      - source: nginx_blue_conf
        target: /etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1

configs:
  nginx_blue_conf:
    file: ./nginx-blue.conf

networks:
  bg-net:
    external: true
