version: "3.9"

services:
  lb:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - bg-net
    command: >
      sh -c "echo 'server { listen 80; location / { proxy_pass http://blue:5678; } }'
      > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    deploy:
      replicas: 1

networks:
  bg-net:
    external: true
