apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-a
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      varient: varient-a
      app: canary
  template:
    metadata:
      labels:
        app: canary
        varient: varient-a
    spec:
      containers:
      - name: canary
      image: nginx:1.25.3